# Site settings
title: "Aref Ghaderi"
email: arefghaderi1372@gmail.com

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
    
plugins:
  - jekyll-sitemap
